/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreatePartArgs } from "./CreatePartArgs";
import { UpdatePartArgs } from "./UpdatePartArgs";
import { DeletePartArgs } from "./DeletePartArgs";
import { PartCountArgs } from "./PartCountArgs";
import { PartFindManyArgs } from "./PartFindManyArgs";
import { PartFindUniqueArgs } from "./PartFindUniqueArgs";
import { Part } from "./Part";
import { Packet } from "../../packet/base/Packet";
import { PartService } from "../part.service";
@graphql.Resolver(() => Part)
export class PartResolverBase {
  constructor(protected readonly service: PartService) {}

  async _partsMeta(
    @graphql.Args() args: PartCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Part])
  async parts(@graphql.Args() args: PartFindManyArgs): Promise<Part[]> {
    return this.service.findMany(args);
  }

  @graphql.Query(() => Part, { nullable: true })
  async part(@graphql.Args() args: PartFindUniqueArgs): Promise<Part | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Part)
  async createPart(@graphql.Args() args: CreatePartArgs): Promise<Part> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        packet: args.data.packet
          ? {
              connect: args.data.packet,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Part)
  async updatePart(@graphql.Args() args: UpdatePartArgs): Promise<Part | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          packet: args.data.packet
            ? {
                connect: args.data.packet,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Part)
  async deletePart(@graphql.Args() args: DeletePartArgs): Promise<Part | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Packet, {
    nullable: true,
    name: "packet",
  })
  async resolveFieldPacket(
    @graphql.Parent() parent: Part
  ): Promise<Packet | null> {
    const result = await this.service.getPacket(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
